### PR TITLE
Automate grabbing latest version of ocserv

### PR DESCRIPTION
**Pull request by MarkusMcNugen**
Use curl, grep, and awk on the ocserv websites changelog to automatically grab the latest version of ocserv when container is built.

### CODE REVIEW

**Comment by MarkusMcNugen** [comment]
I did this for my fork of your container and figured Id help a fellow Docker enthusiast out

**Comment by TommyLau** [comment]
I used to do that way, and some of the dependencies changed, and the build will fail.

So I use the manual way to specific the version number instead.

**Comment by TommyLau** [comment]
You can check this out:
https://github.com/TommyLau/docker-ocserv/commit/f794311869002d5e546223ec448e2377bff3261c

Still thinking whether should make it automatically or not, as the config file is also changed from version to version.

**Comment by MarkusMcNugen** [comment]
Good point. You are right about the config, and youve inspired me to setup my fork of your container a different way. Rather than including a default config that is version specific Im going to copy the default config to my containers /config volume and edit it with sed to match my default configuration. Im already using sed to modify the config based on environmental variables so that cuts out the configuration changing issue for the most part.

**Pull request closed without merging**
