### PR TITLE
user lz4 library in offical repo

### PR DESCRIPTION
**Pull request by CzBiX**
user lz4 library in offical repo
remove unsupported configure options

### CODE REVIEW

**Comment by TommyLau** [comment]
What's the version of liblz4 in the ubuntu repo? The very last time I checked the official repo lz4 cannot be used correctly. And https://github.com/Cyan4973/lz4 is the official source code repo for lz4.

**Comment by CzBiX** [comment]
@TommyLau What's your meaning of "cannot be used correctly"?
The current version of liblz4 in repo can't used to compile, because it missing a file for pkg-config.
We can specify LIBLZ4 flags by manual to resolve it. That's what I do in commit.

**Comment by TommyLau** [comment]
@CzBiX I think you've explained the reason correctly, and I'm curious what's the version of lz4 in the Ubuntu repo?

**Comment by CzBiX** [comment]
我犯了个错误。
我原本尝试在 `Ubuntu:14.04` 上编译 ocserv，发现版本 `0.0~r114-2ubuntu1` 的 `pkg-config` 有问题。然后又注意到你是使用从源码编译的版本，我便以为你也是这个原因。
刚才我才注意到 `debian:jessie` 里的 `0.0~r122-2` 已经修复了此问题，所以没有必要手动指定 configure 参数了。
不知道你碰到的是什么问题？

**Comment by TommyLau** [comment]
时间太长，俨然已经不记得了，囧rz

而且，lz4 的最新版本是 r131，相对来说 r114，r122 还是旧一些。

**Pull request closed without merging**
